last fix for the pres

diff --git a/.github/workflows/worklows.yml b/.github/workflows/worklows.yml
--- a/.github/workflows/worklows.yml
+++ b/.github/workflows/worklows.yml
@@ -72,3 +72,41 @@ jobs:
         run: |
           export $(cat .env.test | xargs)
           npm test
+
+  build:
+    runs-on: ubuntu-latest
+    needs: test # Cette étape dépend de l'étape test pour s'assurer
+    steps:
+      - name: 🛠️ Checkout repository
+        uses: actions/checkout@v4
+
+      - name: 🏗️ Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 22
+          cache: 'npm'
+          cache-dependency-path: eco-task-backend/package-lock.json
+
+      - name: 📦 Install dependencies
+        working-directory: ./eco-task-backend
+        run: npm install
+
+      - name: 📄 Create production environment file
+        working-directory: ./eco-task-backend
+        run: |
+          cp .env.example .env.production
+          sed -i 's/^APP_KEY=.*/APP_KEY=WPcsQJt-IXdhgwTjmCOTPuuTNDcTtFB0/' .env.production
+          sed -i 's/^NODE_ENV=.*/NODE_ENV=production/' .env.production
+      
+      - name: ✅ Verify .env.production file exists
+        working-directory: ./eco-task-backend
+        run: |
+          if [ ! -f .env.production ]; then
+            echo "❌ .env.production file is missing!"
+            exit 1
+          fi
+          cat .env.production
+
+      - name: 🏗️ Build application
+        working-directory: ./eco-task-backend
+        run: npm run build
